export const qDataRaw = [
  {
    isFake: "fake",
    q: "https://i.postimg.cc/s2QR0nTX/1-q.jpg",
    a: "https://i.postimg.cc/wjBzDxJD/1-a.jpg",
    alt: "This is the 1st question alt",
  },
  {
    isFake: "fake",
    q: "https://i.postimg.cc/qqXrxzjx/2-q.jpg",
    a: "https://i.postimg.cc/kXs9VRVn/2-a.png",
    alt: "This is the 2nd question alt",
  },
  {
    isFake: "fake",
    q: "https://i.postimg.cc/m2BB2ygX/3-q.jpg",
    a: "https://i.postimg.cc/Z5DSHkF2/3-a.jpg",
    alt: "this is the 3rd question alt",
  },
  {
    isFake: "legit",
    q: "https://i.postimg.cc/rsmZJQS6/4-q.jpg",
    a: "https://i.postimg.cc/rmqPd8sw/4-a.jpg",
    alt: "this is the 4th question alt",
  },
  {
    isFake: "fake",
    q: "https://i.postimg.cc/x1b7hxBn/5-q.jpg",
    a: "https://i.postimg.cc/mDV6C01N/5-a.jpg",
    alt: "this is the 5th question alt",
  },
  {
    isFake: "fake",
    q: "https://i.postimg.cc/RhDsbKRW/6-q.jpg",
    a: "https://i.postimg.cc/tRSMTGj9/6-a.jpg",
    alt: "this is the 6th question alt",
  },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/RVyGct4N/7-a.jpg",
    q: "https://i.postimg.cc/xC63qJ6j/7-q.jpg",
    alt: "info about",
  },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/mrNwf6MH/8-a.jpg",
    q: "https://i.postimg.cc/43T50TKG/8-q.jpg",
    alt: "info about",
  },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/wvqk6ccb/9-a.jpg",
    q: "https://i.postimg.cc/448WxM0v/9-q.jpg",
    alt: "info about",
  },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/g2hs4024/10-a.jpg",
    q: "https://i.postimg.cc/wT70y2KC/10-q.jpg",
    alt: "info about",
  },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/wM3cNqrX/11-a.jpg",
    q: "https://i.postimg.cc/9F6t4jY9/11-q.jpg",
    alt: "info about",
  },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/SQtGh9XD/12-a.jpg",
    q: "https://i.postimg.cc/dVGRrS5x/12-q.jpg",
    alt: "info about",
  },
  // did not liked it {
  //   isFake: "legit",
  //   a: "https://i.postimg.cc/2yJd7ppP/13-a.jpg",
  //   q: "https://i.postimg.cc/m2zy2rCR/13-q.jpg",
  //   alt: "info about",
  // },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/YSk63fVq/14-a.jpg",
    q: "https://i.postimg.cc/JhqbdHV3/14-q.jpg",
    alt: "info about",
  },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/hjt9F4ck/15-a.jpg",
    q: "https://i.postimg.cc/T1ygwkyQ/15-q.jpg",
    alt: "info about",
  },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/yxw9SFcK/16-a.jpg",
    q: "https://i.postimg.cc/wv4D9KB7/16-q.jpg",
    alt: "info about",
  },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/MKQ1JFJp/17-a.jpg",
    q: "https://i.postimg.cc/QNPcPrPz/17-q.jpg",
    alt: "info about",
  },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/Mp0RvfTk/18-a.jpg",
    q: "https://i.postimg.cc/W1cgNws6/18-q.jpg",
    alt: "info about",
  },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/cJs3Y1gv/19-a.jpg",
    q: "https://i.postimg.cc/fLy02HvZ/19-q.jpg",
    alt: "info about",
  },
  {
    isFake: "legit",
    a: "https://i.postimg.cc/W3yqQM9Z/20-a.jpg",
    q: "https://i.postimg.cc/vm3VvRf3/20-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/gj6Ldn5T/21-a.jpg",
    q: "https://i.postimg.cc/PNspqdnr/21-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/wxS0NJ63/22-a.jpg",
    q: "https://i.postimg.cc/kMVTDwPk/22-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/KvBQDzzf/23-a.jpg",
    q: "https://i.postimg.cc/Z5mH7SvS/23-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/nLckxG1S/24-a.jpg",
    q: "https://i.postimg.cc/nh1kNPqQ/24-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/3wSZx0S8/25-a.jpg",
    q: "https://i.postimg.cc/NMZ71qvZ/25-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/BbD5pYqb/26-a.jpg",
    q: "https://i.postimg.cc/50XSY9Tw/26-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/Vkz99W2s/27-a.jpg",
    q: "https://i.postimg.cc/FFJxhRjv/27-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/Vk4qKbcq/28-a.jpg",
    q: "https://i.postimg.cc/02R0jsfw/28-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/KYznwvZd/29-a.jpg",
    q: "https://i.postimg.cc/nc4YQPRw/29-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/jjFzb02C/30-a.jpg",
    q: "https://i.postimg.cc/XqMdrfwb/30-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/gJL3cSLs/31-a.jpg",
    q: "https://i.postimg.cc/44tpr0gN/31-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/Y01gYv3m/32-a.jpg",
    q: "https://i.postimg.cc/yYH0BT1h/32-q.jpg",
    alt: "info about",
  },
  {
    isFake: "fake",
    a: "https://i.postimg.cc/MKmVGjHC/33-a.jpg",
    q: "https://i.postimg.cc/mgZM12Ft/33-q.jpg",
    alt: "info about",
  },
];
